const bcrypt = require('bcryptjs');
const User = require('../models/User');
const EmergencyService = require('../models/EmergencyService');
const EmergencyContact = require('../models/EmergencyContact');

// Palghar District Headquarters, Maharashtra
const CENTER = { lat: 19.6967, lng: 72.7699 };

const services = [
  // --- HOSPITALS IN PALGHAR & PALGHAR DISTRICT ---
  {
    name: 'Palghar District Civil & Rural Hospital',
    type: 'hospital',
    address: 'Mahim Road, Near Railway Station, Palghar West, Palghar - 401404',
    phone: '+91-2525-252324',
    location: { lat: 19.6974, lng: 72.7672 },
    availability: 'open',
    rating: 4.7,
    facilities: ['Emergency Trauma Unit', 'ICU', 'Blood Bank', '24/7 Casualty', 'Ambulance Bay'],
    emergencyDept: true,
    description: 'Government district headquarters hospital with 24/7 emergency casualty, trauma services, and blood bank.',
  },
  {
    name: 'Philia Hospital & Intensive Care',
    type: 'hospital',
    address: 'Kelve Road, Opp. St. John College, Palghar West, Palghar - 401404',
    phone: '+91-2525-256677',
    location: { lat: 19.6921, lng: 72.7745 },
    availability: 'open',
    rating: 4.6,
    facilities: ['24x7 Emergency', 'Intensive Care Unit (ICU)', 'Cardiac Care', 'Operation Theatre'],
    emergencyDept: true,
    description: 'Multispeciality hospital in Palghar West equipped with modern ICU, cardiac monitoring, and trauma care.',
  },
  {
    name: 'Dr. M. L. Dhawale Memorial Trust Hospital',
    type: 'hospital',
    address: 'Rural Homoeopathic Medical College Campus, Palghar - 401404',
    phone: '+91-2525-256932',
    location: { lat: 19.7042, lng: 72.7788 },
    availability: 'open',
    rating: 4.8,
    facilities: ['Emergency Care', 'Dialysis Unit', 'Surgery', 'Pediatrics', 'Maternity'],
    emergencyDept: true,
    description: 'Premier charitable trust hospital serving Palghar district with round-the-clock emergency medical support.',
  },
  {
    name: 'Anand Hospital & Cardiac Care Unit',
    type: 'hospital',
    address: 'Station Road, Palghar West, Palghar - 401404',
    phone: '+91-2525-251210',
    location: { lat: 19.6995, lng: 72.7681 },
    availability: 'open',
    rating: 4.5,
    facilities: ['Emergency', 'ICU', 'Cardiology', 'Digital X-Ray'],
    emergencyDept: true,
    description: 'Equipped for cardiac emergencies, acute trauma, and intensive medical management.',
  },
  {
    name: 'Astha Hospital & Multispeciality ICU',
    type: 'hospital',
    address: 'Manor Road, Near Shivaji Chowk, Palghar East, Palghar - 401404',
    phone: '+91-2525-253800',
    location: { lat: 19.6980, lng: 72.7731 },
    availability: 'open',
    rating: 4.4,
    facilities: ['Emergency', 'ICU', 'Pathology Lab', 'Pharmacy'],
    emergencyDept: true,
  },
  {
    name: 'Sanjeevani Hospital Boisar',
    type: 'hospital',
    address: 'Navapur Road, Near Railway Station, Boisar West, Palghar - 401501',
    phone: '+91-2525-273111',
    location: { lat: 19.7994, lng: 72.7512 },
    availability: 'open',
    rating: 4.6,
    facilities: ['24/7 Emergency', 'Advanced ICU', 'Trauma Bay', 'Ambulance'],
    emergencyDept: true,
    description: 'Leading multispecialty hospital in Boisar industrial belt handling industrial and general emergencies.',
  },
  {
    name: 'Thunga Multispecialty Hospital Boisar',
    type: 'hospital',
    address: 'Ostwal Empire, Boisar Tarapur Road, Boisar, Palghar - 401501',
    phone: '+91-2525-667788',
    location: { lat: 19.8045, lng: 72.7560 },
    availability: 'open',
    rating: 4.5,
    facilities: ['24x7 Emergency', 'Cath Lab', 'ICU', 'Neuro-trauma'],
    emergencyDept: true,
  },
  {
    name: 'Life Care Hospital & Trauma Centre Boisar',
    type: 'hospital',
    address: 'MIDC Residential Zone, Tarapur, Boisar, Palghar - 401506',
    phone: '+91-2525-270450',
    location: { lat: 19.8110, lng: 72.7440 },
    availability: 'open',
    rating: 4.4,
    facilities: ['Trauma Center', 'Burns Care', 'ICU', 'CT Scan'],
    emergencyDept: true,
  },
  {
    name: 'Sub-District Cottage Hospital Dahanu',
    type: 'hospital',
    address: 'Hospital Road, Near Dahanu Fort, Dahanu, Palghar - 401601',
    phone: '+91-2528-222045',
    location: { lat: 19.9740, lng: 72.7320 },
    availability: 'open',
    rating: 4.5,
    facilities: ['24/7 Casualty', 'Emergency Ward', 'Maternity', 'Ambulance 108'],
    emergencyDept: true,
    description: 'Government sub-district cottage hospital catering to coastal and rural emergencies in Dahanu.',
  },
  {
    name: 'Care Hospital & ICU Dahanu',
    type: 'hospital',
    address: 'Station Road, Dahanu Road West, Palghar - 401602',
    phone: '+91-2528-224466',
    location: { lat: 19.9715, lng: 72.7380 },
    availability: 'open',
    rating: 4.3,
    facilities: ['Emergency', 'ICU', 'Dialysis', 'Operation Theatre'],
    emergencyDept: true,
  },
  {
    name: 'Riddhi Vinayak Multispeciality Hospital Nalasopara',
    type: 'hospital',
    address: 'Achole Road, Near Railway Station, Nalasopara East, Palghar - 401209',
    phone: '+91-250-2432000',
    location: { lat: 19.4185, lng: 72.8220 },
    availability: 'open',
    rating: 4.5,
    facilities: ['24x7 Emergency', 'Cardiac ICU', 'NICU', 'Trauma Unit'],
    emergencyDept: true,
  },
  {
    name: 'Golden Park Hospital Vasai',
    type: 'hospital',
    address: 'Sai Nagar, Ambadi Road, Vasai West, Palghar - 401202',
    phone: '+91-250-2336644',
    location: { lat: 19.3890, lng: 72.8360 },
    availability: 'open',
    rating: 4.6,
    facilities: ['Emergency & Trauma', 'Advanced ICU', 'Orthopedic Surgery', 'Blood Storage'],
    emergencyDept: true,
  },
  {
    name: 'Cardinal Gracias Memorial Hospital Vasai',
    type: 'hospital',
    address: 'Bangli Naka, Vasai West, Palghar - 401201',
    phone: '+91-250-2322300',
    location: { lat: 19.3650, lng: 72.8150 },
    availability: 'open',
    rating: 4.7,
    facilities: ['24/7 Emergency Casualty', 'ICU & CCU', 'CT Scan', 'Pathology'],
    emergencyDept: true,
  },
  {
    name: 'Sahayog Hospital & Research Centre Virar',
    type: 'hospital',
    address: 'Dahisar Road, Near Railway Station, Virar West, Palghar - 401303',
    phone: '+91-250-2500050',
    location: { lat: 19.4680, lng: 72.8090 },
    availability: 'open',
    rating: 4.5,
    facilities: ['Emergency Care', 'ICU', 'Cardiology', 'Orthopedics'],
    emergencyDept: true,
  },
  {
    name: 'Sanjeevani Hospital & ICU Virar',
    type: 'hospital',
    address: 'Manvelpada Road, Virar East, Palghar - 401305',
    phone: '+91-250-2521199',
    location: { lat: 19.4620, lng: 72.8180 },
    availability: 'open',
    rating: 4.4,
    facilities: ['24/7 Emergency', 'ICU', 'Maternity Ward', 'X-Ray'],
    emergencyDept: true,
  },
  {
    name: 'Patangshah Cottage Sub-District Hospital Jawhar',
    type: 'hospital',
    address: 'Rajbhavan Road, Jawhar, Palghar - 401603',
    phone: '+91-2520-222320',
    location: { lat: 19.9231, lng: 73.2325 },
    availability: 'open',
    rating: 4.4,
    facilities: ['Emergency Casualty', 'Maternity', 'Inpatient Ward', 'Ambulance'],
    emergencyDept: true,
  },
  {
    name: 'Rural Hospital Wada',
    type: 'hospital',
    address: 'Khandeshwari Naka, Wada, Palghar - 421303',
    phone: '+91-2526-271224',
    location: { lat: 19.6543, lng: 73.1362 },
    availability: 'open',
    rating: 4.3,
    facilities: ['Emergency Ward', 'Maternity', 'Minor OT', 'General Medicine'],
    emergencyDept: true,
  },
  {
    name: 'Rural Hospital Manor',
    type: 'hospital',
    address: 'NH48 Highway Junction, Manor, Palghar - 401403',
    phone: '+91-2525-265225',
    location: { lat: 19.7423, lng: 72.9135 },
    availability: 'open',
    rating: 4.2,
    facilities: ['Emergency Trauma Care', 'Casualty', 'Ambulance 108'],
    emergencyDept: true,
  },
  {
    name: 'Vedanta Institute of Medical Sciences & Hospital',
    type: 'hospital',
    address: 'Village Dhundhalwadi, NH48 Highway, Talasari, Palghar - 401606',
    phone: '+91-2528-266100',
    location: { lat: 20.0820, lng: 72.9280 },
    availability: 'open',
    rating: 4.6,
    facilities: ['Tertiary Emergency Trauma Care', 'Super-specialty ICU', 'Blood Bank', 'CT/MRI'],
    emergencyDept: true,
  },
  {
    name: 'Palghar PolyClinic & Daycare (Closed Demo)',
    type: 'hospital',
    address: 'Kelve Road, Palghar West, Palghar - 401404',
    phone: '+91-2525-259900',
    location: { lat: 19.6890, lng: 72.7620 },
    availability: 'closed',
    rating: 3.8,
    emergencyDept: false,
  },

  // --- AMBULANCE UNITS IN PALGHAR DISTRICT ---
  {
    name: 'Palghar 108 Emergency Ambulance Hub',
    type: 'ambulance',
    address: 'Civil Hospital Campus, Mahim Road, Palghar West - 401404',
    phone: '108',
    location: { lat: 19.6970, lng: 72.7675 },
    availability: 'open',
    rating: 4.8,
    facilities: ['ALS', 'BLS', 'Oxygen', 'Defibrillator', 'Trained Paramedic'],
    description: 'Government 108 free emergency medical ambulance service stationed at Palghar Civil Hospital.',
  },
  {
    name: 'Boisar MIDC Rapid Response Ambulance',
    type: 'ambulance',
    address: 'Tarapur Fire Station Compound, Boisar, Palghar - 401506',
    phone: '+91-2525-272108',
    location: { lat: 19.8020, lng: 72.7530 },
    availability: 'open',
    rating: 4.7,
    facilities: ['ICU on wheels', 'ALS', 'Industrial Trauma Response'],
  },
  {
    name: 'Vasai-Virar Municipal Emergency Ambulance',
    type: 'ambulance',
    address: 'VVMC Central Dispatch, Virar West, Palghar - 401303',
    phone: '108',
    location: { lat: 19.4660, lng: 72.8110 },
    availability: 'open',
    rating: 4.6,
    facilities: ['ALS', 'BLS', 'Cardiac Monitor'],
  },
  {
    name: 'Dahanu Coastal 108 Ambulance Unit',
    type: 'ambulance',
    address: 'Dahanu Cottage Hospital Bay, Dahanu, Palghar - 401601',
    phone: '108',
    location: { lat: 19.9735, lng: 72.7325 },
    availability: 'open',
    rating: 4.5,
    facilities: ['BLS', 'Oxygen', 'Emergency Stretcher'],
  },

  // --- POLICE STATIONS IN PALGHAR DISTRICT ---
  {
    name: 'Palghar City Police Station',
    type: 'police',
    address: 'Mahim Road, Opp. Collector Office, Palghar - 401404',
    phone: '100',
    location: { lat: 19.6955, lng: 72.7660 },
    availability: 'open',
    rating: 4.3,
    facilities: ['24/7 Control Room', 'Highway Safety Patrol', 'PCR Mobile Vans'],
  },
  {
    name: 'Boisar MIDC Police Station',
    type: 'police',
    address: 'MIDC Area, Tarapur Road, Boisar, Palghar - 401506',
    phone: '+91-2525-272233',
    location: { lat: 19.8060, lng: 72.7480 },
    availability: 'open',
    rating: 4.2,
    facilities: ['24/7 Desk', 'PCR Vans'],
  },
  {
    name: 'Vasai Police Station',
    type: 'police',
    address: 'Vasai Court Road, Vasai West, Palghar - 401201',
    phone: '+91-250-2322333',
    location: { lat: 19.3780, lng: 72.8280 },
    availability: 'open',
    rating: 4.1,
    facilities: ['24/7 Patrol', 'Cyber & Women Helpline'],
  },

  // --- FIRE STATIONS IN PALGHAR DISTRICT ---
  {
    name: 'Palghar Municipal Fire Station',
    type: 'fire',
    address: 'Kelve Road, Near Palghar Municipal Council, Palghar - 401404',
    phone: '101',
    location: { lat: 19.6930, lng: 72.7640 },
    availability: 'open',
    rating: 4.7,
    facilities: ['Water Tenders', 'Rescue Tender', 'High-Rise Ladder'],
  },
  {
    name: 'MIDC Tarapur Fire Station Boisar',
    type: 'fire',
    address: 'MIDC Tarapur Industrial Area, Boisar, Palghar - 401506',
    phone: '+91-2525-272101',
    location: { lat: 19.8080, lng: 72.7460 },
    availability: 'open',
    rating: 4.8,
    facilities: ['Chemical Foam Tender', 'Emergency Rescue Van', 'Hazmat Response'],
  },
  {
    name: 'Vasai-Virar Fire Brigade HQ',
    type: 'fire',
    address: 'Viva College Road, Virar West, Palghar - 401303',
    phone: '101',
    location: { lat: 19.4630, lng: 72.8130 },
    availability: 'open',
    rating: 4.6,
    facilities: ['Hydraulic Platform', 'Emergency Rescue Tender', 'Quick Response Vehicles'],
  },

  // --- 24/7 PHARMACIES IN PALGHAR DISTRICT ---
  {
    name: 'Wellness Forever 24x7 Pharmacy Palghar',
    type: 'pharmacy',
    address: 'Station Road, Opp. ST Bus Stand, Palghar West - 401404',
    phone: '+91-2525-255500',
    location: { lat: 19.6980, lng: 72.7690 },
    availability: 'open',
    rating: 4.6,
    facilities: ['24x7 Prescription', 'Emergency Medicines', 'First Aid', 'Oxygen Cans'],
  },
  {
    name: 'Apollo Pharmacy 24x7 Boisar',
    type: 'pharmacy',
    address: 'Near Railway Station, Boisar West, Palghar - 401501',
    phone: '+91-2525-274400',
    location: { lat: 19.7980, lng: 72.7520 },
    availability: 'open',
    rating: 4.5,
    facilities: ['24x7 Medicines', 'Surgical Supplies', 'Blood Pressure Check'],
  },
  {
    name: 'Noble Chemist & Medical Store Dahanu',
    type: 'pharmacy',
    address: 'Dahanu Road Station, Dahanu, Palghar - 401602',
    phone: '+91-2528-223311',
    location: { lat: 19.9720, lng: 72.7350 },
    availability: 'open',
    rating: 4.4,
    facilities: ['Prescription Drugs', 'Emergency Medical Supplies'],
  },
  {
    name: 'Sanjivani Medico 24x7 Virar',
    type: 'pharmacy',
    address: 'Station Road, Virar West, Palghar - 401303',
    phone: '+91-250-2511222',
    location: { lat: 19.4690, lng: 72.8070 },
    availability: 'open',
    rating: 4.5,
    facilities: ['24x7 Dispensing', 'First Aid', 'Injectables'],
  },
];

async function seedDatabase({ reset = false } = {}) {
  const count = await EmergencyService.countDocuments();
  if (count > 0 && !reset) {
    return { seeded: false, reason: 'already-populated' };
  }

  if (reset) {
    await EmergencyService.deleteMany({});
    await EmergencyContact.deleteMany({});
    await User.deleteMany({ email: 'demo@ailea.app' });
  }

  const docs = services.map((s) => ({
    ...s,
    location: {
      type: 'Point',
      coordinates: [s.location.lng, s.location.lat],
    },
  }));

  await EmergencyService.insertMany(docs);

  const passwordHash = await bcrypt.hash('demo1234', 10);
  const user = await User.create({
    name: 'Demo User',
    email: 'demo@ailea.app',
    phone: '+91-98765-43210',
    passwordHash,
    preferences: {
      language: 'en',
      notifications: true,
      shareLocationOnSos: true,
    },
    location: {
      lat: CENTER.lat,
      lng: CENTER.lng,
      label: 'Palghar, Maharashtra',
      city: 'Palghar',
      district: 'Palghar',
      state: 'Maharashtra',
      updatedAt: new Date(),
    },
  });

  await EmergencyContact.insertMany([
    {
      userId: user._id,
      name: 'Rahul Patil (Brother)',
      phone: '+91-98230-11111',
      relationship: 'Family',
      priority: 1,
      notifyOnSos: true,
    },
    {
      userId: user._id,
      name: 'Dr. Sneha Joshi (Family Physician, Palghar)',
      phone: '+91-98230-22222',
      relationship: 'Other',
      priority: 2,
      notifyOnSos: true,
    },
    {
      userId: user._id,
      name: 'Amit Sharma (Neighbor - Palghar West)',
      phone: '+91-98230-33333',
      relationship: 'Neighbor',
      priority: 3,
      notifyOnSos: true,
    },
  ]);

  return { seeded: true, services: docs.length };
}

module.exports = { seedDatabase, CENTER, services };
